import { 
  Building2, 
  Cpu, 
  Activity, 
  Dna, 
  Anchor, 
  Compass, 
  Sprout, 
  Zap, 
  Layers, 
  Boxes, 
  Send, 
  Train, 
  Satellite,
  Waves,
  Bot
} from 'lucide-react';

export const CITY_DISTRICTS = [
  {
    id: "raie_lab",
    name: "ARCS - RAIE Innovation Lab & Smart Kit",
    shortLabel: "RAIE Lab",
    icon: Bot,
    category: "Robotics & AI Lab",
    color: "#00F2FE",
    accentColor: "#38BDF8",
    position: [16, 2, -15],
    markerOffset: [0, 9.5, 0],
    hologramOffset: [12, 14, 8],
    cameraTarget: {
      position: [32, 18, 5],
      lookAt: [16, 4, -15]
    },
    useCaseIds: ["t6-u1", "t9-u1"],
    primaryCaseId: "t6-u1",
    tagline: "Research Academy of Innovation & Excellence: 12 embodied robotics systems, Smart Kit hardware toolkit & virtual lab.",
    simulationType: "Embodied Robotics & Smart Kit Twin",
    simulationStatus: "ROS2 & Hardware Loop Active",
    technologies: ["LeRobot SO-ARM101", "JetTank SLAM", "Ainex Humanoid", "JetHexa", "CubeSat Gen 2", "Bambu Lab 3D", "Smart Kit 4WD", "Meta Quest 3"]
  },
  {
    id: "commercial",
    name: "Commercial Real Estate & GCC Tech Center",
    shortLabel: "Commercial Real Estate",
    icon: Building2,
    category: "Infrastructure",
    color: "#00F2FE",
    accentColor: "#38BDF8",
    position: [0, 3, 0],
    markerOffset: [0, 16, 0],
    hologramOffset: [-14, 16, 8],
    cameraTarget: {
      position: [18, 28, 24],
      lookAt: [-4, 7, -2]
    },
    useCaseIds: ["t3-u2"],
    primaryCaseId: "t3-u2",
    tagline: "BIM alignment, drone photogrammetry & live digital construction drift monitoring.",
    simulationType: "3D BIM Drift Detection",
    simulationStatus: "Photogrammetry Stream Live",
    technologies: ["BIM / IFC", "Photogrammetry", "LiDAR", "OpenUSD", "Computer Vision"]
  },
  {
    id: "manufacturing",
    name: "Manufacturing & Robotics Hub",
    shortLabel: "Manufacturing",
    icon: Cpu,
    category: "Industrial Automation",
    color: "#7928CA",
    accentColor: "#A855F7",
    position: [-24, 3, -26],
    markerOffset: [0, 8, 0],
    hologramOffset: [-10, 14, 10],
    cameraTarget: {
      position: [-10, 20, -8],
      lookAt: [-24, 3, -26]
    },
    useCaseIds: ["t6-u1", "t6-u2"],
    primaryCaseId: "t6-u1",
    tagline: "AI-driven robotic assembly, continuous kinematic optimization & real-time quality inspection.",
    simulationType: "Robotic Assembly Optimization",
    simulationStatus: "AI Kinematic Engine Active",
    technologies: ["Robotics", "Computer Vision", "Isaac Sim", "NVIDIA Omniverse", "Edge AI"]
  },
  {
    id: "healthcare",
    name: "Healthcare & Medical Technology Campus",
    shortLabel: "Healthcare",
    icon: Activity,
    category: "Healthcare",
    color: "#FF2E93",
    accentColor: "#F43F5E",
    position: [-24, 3, 26],
    markerOffset: [0, 9, 0],
    hologramOffset: [-10, 14, 10],
    cameraTarget: {
      position: [-8, 20, 44],
      lookAt: [-24, 3, 26]
    },
    useCaseIds: ["t2-u1", "t2-u2"],
    primaryCaseId: "t2-u1",
    tagline: "AI-powered ICU organ digital twins and real-time AR-guided surgical navigation.",
    simulationType: "Dynamic Organ Hemodynamics",
    simulationStatus: "Live Vitals Telemetry Synced",
    technologies: ["Medical IoT", "HL7 / FHIR", "DICOM", "TensorRT", "AR Overlays"]
  },
  {
    id: "biotech",
    name: "Biotechnology & Biosphere Labs",
    shortLabel: "Biotech Research",
    icon: Dna,
    category: "Biotechnology",
    color: "#00F2FE",
    accentColor: "#06B6D4",
    position: [28, 3, -26],
    markerOffset: [0, 8, 0],
    hologramOffset: [12, 14, 8],
    cameraTarget: {
      position: [44, 20, -8],
      lookAt: [28, 3, -26]
    },
    useCaseIds: ["t1-u1", "t1-u2"],
    primaryCaseId: "t1-u1",
    tagline: "Sensor-driven bioreactor digital twins and AR-assisted computer vision pipetting assistance.",
    simulationType: "Fermentation Yield Prediction",
    simulationStatus: "Bio-Sensor Loop Active",
    technologies: ["IoT Sensors", "OPC UA / MQTT", "DeepStream", "Omniverse", "OpenXR"]
  },
  {
    id: "ports",
    name: "Smart Ports & Deepwater Maritime Harbor",
    shortLabel: "Ports & Harbor",
    icon: Anchor,
    category: "Logistics & Maritime",
    color: "#00E1D9",
    accentColor: "#0EA5E9",
    position: [-80, 1.8, -26],
    markerOffset: [0, 9, 0],
    hologramOffset: [-14, 15, 12],
    cameraTarget: {
      position: [-62, 22, -4],
      lookAt: [-80, 2, -26]
    },
    useCaseIds: ["t10-u1"],
    primaryCaseId: "t10-u1",
    tagline: "Automated container gantry operations, tide monitoring and live berthing digital replicas.",
    simulationType: "Vessel Berthing & Container Logistics",
    simulationStatus: "AIS & Port Telemetry Live",
    technologies: ["AIS Telemetry", "SAR Radar", "GIS Mapping", "Omniverse", "Edge Computing"]
  },
  {
    id: "mining",
    name: "Mining & Energy Subsurface Quarry",
    shortLabel: "Mining & Energy",
    icon: Compass,
    category: "Mining",
    color: "#FF7849",
    accentColor: "#F97316",
    position: [34, 10, -94],
    markerOffset: [0, 11, 0],
    hologramOffset: [12, 16, 10],
    cameraTarget: {
      position: [50, 28, -70],
      lookAt: [34, 8, -94]
    },
    useCaseIds: ["t8-u1", "t8-u2"],
    primaryCaseId: "t8-u1",
    tagline: "Subterranean gas & structural sensors with AR remote expert collaboration in deep shafts.",
    simulationType: "Atmospheric Methane Monitoring",
    simulationStatus: "Mesh Sensor Network Live",
    technologies: ["Subsurface IoT", "Mesh Networks", "SCADA", "Thermal Vision", "OpenUSD"]
  },
  {
    id: "agriculture",
    name: "Smart Agriculture & Precision Farming",
    shortLabel: "Smart Farming",
    icon: Sprout,
    category: "Agriculture",
    color: "#05FFA1",
    accentColor: "#10B981",
    position: [88, 3, 28],
    markerOffset: [0, 8, 0],
    hologramOffset: [14, 14, 10],
    cameraTarget: {
      position: [106, 26, 52],
      lookAt: [88, 3, 28]
    },
    useCaseIds: ["t4-u1", "t4-u2"],
    primaryCaseId: "t4-u1",
    tagline: "Automated closed-loop irrigation, soil-moisture heatmaps and on-plant AR disease diagnosis.",
    simulationType: "Soil Moisture AI Forecasting",
    simulationStatus: "Irrigation Telemetry Active",
    technologies: ["LoRaWAN", "Soil Sensors", "Edge AI", "Computer Vision", "GIS Heatmaps"]
  },
  {
    id: "grid",
    name: "Smart Electrical Substation & Power Grid",
    shortLabel: "Power Grid",
    icon: Zap,
    category: "Energy",
    color: "#FFE600",
    accentColor: "#FBBF24",
    position: [90, 3, -55],
    markerOffset: [0, 9, 0],
    hologramOffset: [12, 15, 10],
    cameraTarget: {
      position: [106, 24, -32],
      lookAt: [90, 3, -55]
    },
    useCaseIds: ["t5-u1", "t5-u2"],
    primaryCaseId: "t5-u1",
    tagline: "Virtual breaker switching simulation, load-flow risk modeling and AR electrical panel inspection.",
    simulationType: "Virtual Load Flow & Switching",
    simulationStatus: "IEC 61850 Stream Connected",
    technologies: ["SCADA / RTU", "IEC 61850", "Power Simulation", "Thermal Vision", "Omniverse"]
  },
  {
    id: "warehousing",
    name: "Walmart Distribution Center & Logistics",
    shortLabel: "Walmart DC Hub",
    icon: Boxes,
    category: "Logistics",
    color: "#38EF7D",
    accentColor: "#22C55E",
    position: [-70, 3, 8],
    markerOffset: [0, 8, 0],
    hologramOffset: [-14, 14, 12],
    cameraTarget: {
      position: [-52, 22, 26],
      lookAt: [-70, 3, 8]
    },
    useCaseIds: ["t10-u1"],
    primaryCaseId: "t10-u1",
    tagline: "Fleet-wide multi-agent AMR path optimization, 53ft trailer staging and cross-docking.",
    simulationType: "AMR Multi-Agent Route Planning",
    simulationStatus: "24/30 Robots Synchronized",
    technologies: ["AMRs / AGVs", "Isaac Sim", "LiDAR", "ROS 2 / MQTT", "Edge Gateway"]
  },
  {
    id: "drones",
    name: "Autonomous Drone Delivery Station",
    shortLabel: "Drone Vertiport",
    icon: Send,
    category: "Autonomous Logistics",
    color: "#00F2FE",
    accentColor: "#38BDF8",
    position: [-20, 3, 85],
    markerOffset: [0, 9, 0],
    hologramOffset: [-12, 14, 10],
    cameraTarget: {
      position: [-2, 22, 108],
      lookAt: [-20, 3, 85]
    },
    useCaseIds: ["t10-u2"],
    primaryCaseId: "t10-u2",
    tagline: "Vertiport air corridor dispatch, multi-stop citywide parcel delivery and battery swap telemetry.",
    simulationType: "Aerial Corridor Fleet Telemetry",
    simulationStatus: "MAVLink Sky Link Live",
    technologies: ["MAVLink / 5G", "GNSS / RTK", "3D City Twin", "Thermal Sensors", "OpenXR"]
  },
  {
    id: "additive",
    name: "Additive Manufacturing & 3D Lab",
    shortLabel: "3D Printing Lab",
    icon: Layers,
    category: "Advanced Manufacturing",
    color: "#00DFD8",
    accentColor: "#14B8A6",
    position: [16, 3, 85],
    markerOffset: [0, 9, 0],
    hologramOffset: [12, 14, 8],
    cameraTarget: {
      position: [34, 22, 108],
      lookAt: [16, 3, 85]
    },
    useCaseIds: ["t9-u1", "t9-u2"],
    primaryCaseId: "t9-u1",
    tagline: "Real-time layer defect detection, melt-pool monitoring and AR CAD-to-part alignment metrology.",
    simulationType: "Layer-by-Layer In-Situ Metrology",
    simulationStatus: "Computer Vision Active",
    technologies: ["Computer Vision", "CAD Digital Twin", "Marlin / Klipper API", "Edge PC", "TensorRT"]
  },
  {
    id: "rail",
    name: "Smart Rail, Metro & Suspension Bridge",
    shortLabel: "Rail & Metro",
    icon: Train,
    category: "Transportation",
    color: "#FFB800",
    accentColor: "#F59E0B",
    position: [-24, 5.5, 0],
    markerOffset: [0, 8, 0],
    hologramOffset: [-12, 14, 10],
    cameraTarget: {
      position: [-6, 22, 20],
      lookAt: [-24, 5, 0]
    },
    useCaseIds: ["t3-u1"],
    primaryCaseId: "t3-u1",
    tagline: "Connected suspension bridge structural health digital twins with strain gauges & accelerometers.",
    simulationType: "Modal Vibration Frequency Twin",
    simulationStatus: "Strain Telemetry Streaming",
    technologies: ["Strain Gauges", "Accelerometers", "LoRaWAN", "Jetson Edge", "Omniverse"]
  },
  {
    id: "disaster",
    name: "Disaster Response & Flood Defense Operations",
    shortLabel: "Disaster & Flood Defense",
    icon: Satellite,
    category: "Emergency Intelligence",
    color: "#00E1D9",
    accentColor: "#06B6D4",
    position: [-16, 3, -76],
    markerOffset: [0, 9, 0],
    hologramOffset: [-12, 15, 10],
    cameraTarget: {
      position: [4, 22, -54],
      lookAt: [-16, 3, -76]
    },
    useCaseIds: ["t7-u1", "t7-u2"],
    primaryCaseId: "t7-u1",
    tagline: "Satellite & drone flood-extent modeling, AI inundation forecasting, and AR field rescue coordination.",
    simulationType: "AI Flood Spread & SAR Rescue",
    simulationStatus: "Flood Hydrology & Drone Streams Active",
    technologies: ["SAR Satellite", "Hydro IoT Sensors", "Thermal Drones", "Spatial SLAM", "WebRTC"]
  },
  {
    id: "fishfarm",
    name: "Smart Aquaculture & Offshore Fish Farm",
    shortLabel: "Fish Farm & Aquaculture",
    icon: Waves,
    category: "Aquaculture & Marine",
    color: "#00E5FF",
    accentColor: "#06B6D4",
    position: [-96, 2, 32],
    markerOffset: [0, 9, 0],
    hologramOffset: [-12, 14, 10],
    cameraTarget: {
      position: [-76, 22, 54],
      lookAt: [-96, 1, 32]
    },
    useCaseIds: ["t4-u2"],
    primaryCaseId: "t4-u2",
    liveDemoUrl: "https://fdt-fawn.vercel.app",
    liveDemoTitle: "AI-Powered Fish Farming & Smart Aquaculture Live Digital Twin",
    tagline: "Autonomous offshore sea cages, dissolved oxygen telemetry, Isaac Sim ROV net inspection & Cosmos biomass AI.",
    simulationType: "Ocean Biomass & Water Quality AI",
    simulationStatus: "DO & Salinity Telemetry Live",
    technologies: ["NVIDIA Omniverse", "Isaac Sim", "NVIDIA Cosmos", "Edge Jetson", "DO / Salinity IoT"]
  },
  {
    id: "pigfarm",
    name: "Smart Livestock & Pig Farmstead",
    shortLabel: "Pig Farm & Livestock",
    icon: Sprout,
    category: "Livestock & Agriculture",
    color: "#FF6B8B",
    accentColor: "#F43F5E",
    position: [45, 2, 85],
    markerOffset: [0, 8, 0],
    hologramOffset: [12, 14, 8],
    cameraTarget: {
      position: [64, 22, 106],
      lookAt: [45, 1, 85]
    },
    useCaseIds: ["t4-u1"],
    primaryCaseId: "t4-u1",
    liveDemoUrl: "https://pigfarm-teal.vercel.app",
    liveDemoTitle: "AI-Powered Swine Health & Livestock Live Digital Twin",
    tagline: "NVIDIA Cosmos foundation models & Omniverse USD barn digital twin for swine motion synthesis and edge AI disease detection.",
    simulationType: "Livestock Vitals & Disease AI",
    simulationStatus: "Lethargy Vision Model Active",
    technologies: ["NVIDIA Omniverse", "NVIDIA Cosmos", "TAO Toolkit", "Jetson Edge", "Omniverse Replicator"]
  }
];

export const CITY_DEFAULT_VIEW = {
  position: [72, 80, 98],
  lookAt: [0, 3, 0]
};
